service: alexa-radio-skill

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1  # The region where your skill is hosted

functions:
  radioSkill:
    handler: lambda/index.handler
    memorySize: 128
    timeout: 10
    events:
      - alexaSkill:  # Automatically connects with the Alexa Skill
          appId: "YOUR_SKILL_ID"

plugins:
  - serverless-alexa-skills
