service: alexa-radio-skill

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1  # The region where your skill is hosted

functions:
  radioSkill:
    handler: lambda/index.handler
    memorySize: 128
    timeout: 10
    events:
      - alexaSkill:  # Automatically connects with the Alexa Skill
          appId: "amzn1.ask.skill.9768837c-d364-425a-9b9f-31be7b1bced3"

plugins:
  - serverless-alexa-skills
